name: Enviroment Variable - Secrets

on: workflow_dispatch

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: My step
        env:
          BROKERS: ${{ secrets.BROKERS }}
          CONFIG_URL: ${{ secrets.CONFIG_URL }}
          DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
          DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
          DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
          DEFAULT_ZONE: ${{ secrets.DEFAULT_ZONE }}
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
          IP_ADDRESS: ${{ secrets.IP_ADDRESS }}
        run: |
          echo BROKERS
          echo CONFIG_URL
          echo DATASOURCE_PASSWORD
          echo DATASOURCE_URL
          echo DATASOURCE_USERNAME
          echo DEFAULT_ZONE
          echo FIREBASE_KEY
          echo IP_ADDRESS
